### ISSUE TITLE
Bug: Caching invalidation with filemtime()

### ISSUE THREAD

**Issue by vf-telwing** [iconify-design/json-tools.php#1]
Hello!

I am facing an issue where my cache file is refreshed on every page load. I think this is due to the fact that the most recent file time cannot be stored in the cache file itself.

For example, in `Collection::loadFromFile()`, the file time is coming from `filemtime()`, but as soon as `Collection::saveCache()` finishes and `file_put_contents()` runs, the file time has already been updated and the time in the cache file is invalid.

I think the current approach always runs into this issue where `file_put_contents()` updates the modification time after the cache file has already been written and the next time we try to use `filemtime()` to load from cache, `Collection::loadFromCache()` always returns false.

One solution could be to `touch()` the cache file to reset the modification time to the expected value:

```php
// Collection.php
public function saveCache($filename, $fileTime)
{
    // ...
    file_put_contents($filename, $content);
    @chmod($filename, 0644);
    // Reset the modification time
    touch($filename, $fileTime);
}
```

Please let me know if I am misunderstanding something or am not using it properly.

**Comment by cyberalien** [comment]
I think you have confused different files. Variable `$fileTime` is not time stamp of cache file, it is time stamp of original json file. It is used to invalidate cache if original json file changes. See function `loadFromFile`.

**Comment by vf-telwing** [comment]
My apologies, that makes much more sense. Thank you for the explanation.
